uaa-server: http://localhost:8080/
server:
  port: 8080
security:
  oauth2:
    client:
      client-secret: 9VvJvgaImYgC61Eyx3g0fFtMn0Yu1FdijU43BgPF5ZP8DhYpUmM9Fhye9NdV2C8t5nFz8nsOznonK+DDPDFgBg==
      scope: all
      access-token-uri: https://checking.cdiisp.com:8800/uias/sso/getAccessToken
      grant-type: client_credentials
      token-name: accessToken
      client-id: gxdj
      client-authentication-scheme: header
      authentication-scheme: header
debug: true
spring:
  main:
    allow-bean-definition-overriding: true